services:
  backend:
    environment:
      - ENV=debug
      - DEBUG=true
    command: uvicorn apps.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./be_src:/app
  frontend:
    environment:
      - ENV=debug
    volumes:
      - ./fe_src:/app
